// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Pietroski/SimpleTransactionDemo/pkg/mocks/validator-v10 (interfaces: FieldLevelValidator)

// Package mocked_validator_v10 is a generated GoMock package.
package mocked_validator_v10

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFieldLevelValidator is a mock of FieldLevelValidator interface.
type MockFieldLevelValidator struct {
	ctrl     *gomock.Controller
	recorder *MockFieldLevelValidatorMockRecorder
}

// MockFieldLevelValidatorMockRecorder is the mock recorder for MockFieldLevelValidator.
type MockFieldLevelValidatorMockRecorder struct {
	mock *MockFieldLevelValidator
}

// NewMockFieldLevelValidator creates a new mock instance.
func NewMockFieldLevelValidator(ctrl *gomock.Controller) *MockFieldLevelValidator {
	mock := &MockFieldLevelValidator{ctrl: ctrl}
	mock.recorder = &MockFieldLevelValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFieldLevelValidator) EXPECT() *MockFieldLevelValidatorMockRecorder {
	return m.recorder
}

// ExtractType mocks base method.
func (m *MockFieldLevelValidator) ExtractType(arg0 reflect.Value) (reflect.Value, reflect.Kind, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractType", arg0)
	ret0, _ := ret[0].(reflect.Value)
	ret1, _ := ret[1].(reflect.Kind)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// ExtractType indicates an expected call of ExtractType.
func (mr *MockFieldLevelValidatorMockRecorder) ExtractType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractType", reflect.TypeOf((*MockFieldLevelValidator)(nil).ExtractType), arg0)
}

// Field mocks base method.
func (m *MockFieldLevelValidator) Field() reflect.Value {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Field")
	ret0, _ := ret[0].(reflect.Value)
	return ret0
}

// Field indicates an expected call of Field.
func (mr *MockFieldLevelValidatorMockRecorder) Field() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Field", reflect.TypeOf((*MockFieldLevelValidator)(nil).Field))
}

// FieldName mocks base method.
func (m *MockFieldLevelValidator) FieldName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FieldName")
	ret0, _ := ret[0].(string)
	return ret0
}

// FieldName indicates an expected call of FieldName.
func (mr *MockFieldLevelValidatorMockRecorder) FieldName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FieldName", reflect.TypeOf((*MockFieldLevelValidator)(nil).FieldName))
}

// GetStructFieldOK mocks base method.
func (m *MockFieldLevelValidator) GetStructFieldOK() (reflect.Value, reflect.Kind, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructFieldOK")
	ret0, _ := ret[0].(reflect.Value)
	ret1, _ := ret[1].(reflect.Kind)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetStructFieldOK indicates an expected call of GetStructFieldOK.
func (mr *MockFieldLevelValidatorMockRecorder) GetStructFieldOK() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructFieldOK", reflect.TypeOf((*MockFieldLevelValidator)(nil).GetStructFieldOK))
}

// GetStructFieldOK2 mocks base method.
func (m *MockFieldLevelValidator) GetStructFieldOK2() (reflect.Value, reflect.Kind, bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructFieldOK2")
	ret0, _ := ret[0].(reflect.Value)
	ret1, _ := ret[1].(reflect.Kind)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(bool)
	return ret0, ret1, ret2, ret3
}

// GetStructFieldOK2 indicates an expected call of GetStructFieldOK2.
func (mr *MockFieldLevelValidatorMockRecorder) GetStructFieldOK2() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructFieldOK2", reflect.TypeOf((*MockFieldLevelValidator)(nil).GetStructFieldOK2))
}

// GetStructFieldOKAdvanced mocks base method.
func (m *MockFieldLevelValidator) GetStructFieldOKAdvanced(arg0 reflect.Value, arg1 string) (reflect.Value, reflect.Kind, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructFieldOKAdvanced", arg0, arg1)
	ret0, _ := ret[0].(reflect.Value)
	ret1, _ := ret[1].(reflect.Kind)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetStructFieldOKAdvanced indicates an expected call of GetStructFieldOKAdvanced.
func (mr *MockFieldLevelValidatorMockRecorder) GetStructFieldOKAdvanced(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructFieldOKAdvanced", reflect.TypeOf((*MockFieldLevelValidator)(nil).GetStructFieldOKAdvanced), arg0, arg1)
}

// GetStructFieldOKAdvanced2 mocks base method.
func (m *MockFieldLevelValidator) GetStructFieldOKAdvanced2(arg0 reflect.Value, arg1 string) (reflect.Value, reflect.Kind, bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructFieldOKAdvanced2", arg0, arg1)
	ret0, _ := ret[0].(reflect.Value)
	ret1, _ := ret[1].(reflect.Kind)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(bool)
	return ret0, ret1, ret2, ret3
}

// GetStructFieldOKAdvanced2 indicates an expected call of GetStructFieldOKAdvanced2.
func (mr *MockFieldLevelValidatorMockRecorder) GetStructFieldOKAdvanced2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructFieldOKAdvanced2", reflect.TypeOf((*MockFieldLevelValidator)(nil).GetStructFieldOKAdvanced2), arg0, arg1)
}

// GetTag mocks base method.
func (m *MockFieldLevelValidator) GetTag() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTag indicates an expected call of GetTag.
func (mr *MockFieldLevelValidatorMockRecorder) GetTag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockFieldLevelValidator)(nil).GetTag))
}

// Param mocks base method.
func (m *MockFieldLevelValidator) Param() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Param")
	ret0, _ := ret[0].(string)
	return ret0
}

// Param indicates an expected call of Param.
func (mr *MockFieldLevelValidatorMockRecorder) Param() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Param", reflect.TypeOf((*MockFieldLevelValidator)(nil).Param))
}

// Parent mocks base method.
func (m *MockFieldLevelValidator) Parent() reflect.Value {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parent")
	ret0, _ := ret[0].(reflect.Value)
	return ret0
}

// Parent indicates an expected call of Parent.
func (mr *MockFieldLevelValidatorMockRecorder) Parent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parent", reflect.TypeOf((*MockFieldLevelValidator)(nil).Parent))
}

// StructFieldName mocks base method.
func (m *MockFieldLevelValidator) StructFieldName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StructFieldName")
	ret0, _ := ret[0].(string)
	return ret0
}

// StructFieldName indicates an expected call of StructFieldName.
func (mr *MockFieldLevelValidatorMockRecorder) StructFieldName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StructFieldName", reflect.TypeOf((*MockFieldLevelValidator)(nil).StructFieldName))
}

// Top mocks base method.
func (m *MockFieldLevelValidator) Top() reflect.Value {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Top")
	ret0, _ := ret[0].(reflect.Value)
	return ret0
}

// Top indicates an expected call of Top.
func (mr *MockFieldLevelValidatorMockRecorder) Top() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Top", reflect.TypeOf((*MockFieldLevelValidator)(nil).Top))
}
