// Code generated by sqlc. DO NOT EDIT.

package bank_account_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetPaginatedUserWallets(ctx context.Context, arg GetPaginatedUserWalletsParams) ([]Wallet, error)
	GetPaginatedWalletsByUserID(ctx context.Context, arg GetPaginatedWalletsByUserIDParams) ([]Wallet, error)
	GetUserWallets(ctx context.Context, userID uuid.UUID) ([]Wallet, error)
	GetWalletsByUserID(ctx context.Context, userID uuid.UUID) ([]Wallet, error)
	ListFromUserTransactionLogs(ctx context.Context, fromUserID uuid.UUID) ([]TransactionRecord, error)
	ListPaginatedFromUserTransactionLogs(ctx context.Context, arg ListPaginatedFromUserTransactionLogsParams) ([]TransactionRecord, error)
	ListPaginatedToUserTransactionLogs(ctx context.Context, arg ListPaginatedToUserTransactionLogsParams) ([]TransactionRecord, error)
	ListPaginatedTransactionLogs(ctx context.Context, arg ListPaginatedTransactionLogsParams) ([]TransactionRecord, error)
	ListToUserTransactionLogs(ctx context.Context, toUserID uuid.UUID) ([]TransactionRecord, error)
	ListTransactionLogs(ctx context.Context) ([]TransactionRecord, error)
	LogTransaction(ctx context.Context, arg LogTransactionParams) (TransactionRecord, error)
	UpdateUserWalletBalance(ctx context.Context, arg UpdateUserWalletBalanceParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
