version: '3.8'
services:
  simple-transaction-demo-playground-db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=manager
      - POSTGRES_DB=playground_db
    ports:
      - '5432:5432'
    volumes:
      - simple-transaction-demo-playground-db:/var/lib/postgresql/data
volumes:
  simple-transaction-demo-playground-db:
    driver: local
